### PR TITLE
Allow for DefaultLockRetryTime to be overriden by options

### PR DESCRIPTION
**Pull request by pfrejlich**

### CODE REVIEW

**Comment by highlyunavailable** [comment]
What is the primary driving need for this PR?

The current reason it is set is to avoid a hot loop trying to acquire a lock - changing this to a smaller value should also be bounded somehow so that it can't be set to 0 (causing a hot loop).

**Comment by pfrejlich** [comment]
Hi and thank you for your fast reply in regards to my PR.

Few reasons behind it.

First, consistency. All other parameters can be set at the options level
except this one.

Second, even though the purpose of that value is clear, might not fit every
scenario. In our case we have a handful of tasks that execute quite fast
but access occasionally a shared resource that will be in contention. If we
leave the original value as is, most tasks will be idle waiting for next
attempt to acquire the lock.

In other scenarios, depending on the executing action, it might make sense
to delay lock acquiring even more than default value.

My point is, there are scenarios where default value might not fit, leaving
the user with no choice. I agree though that adding a check whether the
time span was set to 0 or not will prevent undesired behavior.

Thanks,
Pablo

**Comment by highlyunavailable** [comment]
All good points. The only reason it isn't configurable is the Go API doesn't allow it to be configured:
https://github.com/hashicorp/consul/blob/master/api/lock.go#L228 but that's not a good reason at all to not have this user-settable.

If you could add a setter and check to see if the time is something sane, like a minimum of 500ms or 1000ms, throwing the appropriate exception if it isn't above that minimum (no maximum is needed) I'll be happy to accept this PR. Thanks!

**Comment by pfrejlich** [comment]
Done.

Let me know if you think the code is fine from your perspective or you
would like further adjustments.

Thanks,
Pablo

**Comment by highlyunavailable** [comment]
`MonitorRetryTime` is not `LockRetryTime` - you added a setter for MonitorRetryTime instead.

I've corrected this and added a test - thanks for the contribution.

**Pull request merged**
