### PR TITLE
Added meta dictionary to the service payloads of the agent API

### PR DESCRIPTION
**Pull request by brunodfg**
For issue #119

### CODE REVIEW

**Comment by anwright-ms** [comment]
Have you tried this out with a response that contains the dictionary? I wasn't aware json.net could deserialize into interfaces - should this be just `Dictionary` instead?

**Comment by brunodfg** [comment]
Yes, I tried and seems to work well. It's the same property as the one which already exists in  CatalogService.cs. 

In any case, I'm happy to change them to concrete Dictionary types.

**Comment by brunodfg** [comment]
Cool! Thanks. Would it be possible to get the nuget package updated with the latest code, please?

**Comment by anwright-ms** [comment]
Yep, it's released now. I was leaving for work when I merged this so it took a bit to cut the release.

**Pull request merged**
