### PR TITLE
Update Newtonsoft.Json to version 7.0.1

### PR DESCRIPTION
**Pull request by freein**

### CODE REVIEW

**Comment by freein** [comment]
In order to be able use Nest (http://nest.azurewebsites.net/) side by side with this library without binding redirect this update is preferred.

All tests execute just fine.

**Comment by highlyunavailable** [comment]
Hmm, this is an interesting request. I know the original users (PlayFab) use Json.net 6.0.8 so this would break some stuff for them. I also can't currently maintain this library since I've since left PlayFab and am no longer a contributor on this repo.

@hungwunfai Do you want to take over contributor (or give me repo access to do so)? This directly affects your config service if this PR is merged.

**Comment by hungwunfai** [comment]
@highlyunavailable Sure I will take it over. I think we are fine. We have updated JSON.NET to 7.0.1 recently. In case we have problem, we can always revert to an older version of ConsulDotNet.

**Comment by highlyunavailable** [comment]
Okay, cool.

**Comment by freein** [comment]
Nice. :+1:  Can you possibly create a nuget package so I can use it immediately?

**Comment by highlyunavailable** [comment]
@freein Looks like everything built - https://www.nuget.org/packages/Consul has the new package.

Thanks for your help @hungwunfai - I'll let you respond to PRs from now on.

**Pull request merged**
